ftype: 'softmax'
btype: 'minibatch'
update_type: 'nag'
reg: true
gamma: 0.01
maxloss: 1.0
maxsteps: 1000
batch_size: 64
learning_rate: 1e-7
mu: 0.9
beta1: 0.9
beta2: 0.999
verbose: true
gradcheckstep: 1e-6
num_checks: 3
