ftype: 'softmax'
btype: 'minibatch'
update_type: 'sgd'
reg: true
gamma: 0.01
maxloss: 1.0
maxsteps: 1000
batch_size: 8
learning_rate: 1.0e-03
lr_decay: 0.95
mu: 0.9
beta1: 0.9
beta2: 0.999
verbose: true
gradcheckstep: 1.0e-06
num_checks: 3
eps: 1.0e-08
aini: 2.0
bini: 0.01
