ftype: 'softmax'
btype: 'minibatch'
update_type: 'nag'
reg: true
gamma: 0.001
maxloss: 1.0
maxsteps: 1000
batch_size: 1024
learning_rate: 2.0e-07
mu: 0.9
beta1: 0.9
beta2: 0.999
verbose: true
gradcheckstep: 1.0e-06
num_checks: 3
