ftype: 'softmax'
btype: 'minibatch'
update_type: 'adam'
reg: true
gamma: 0.001
maxloss: 0.2
maxsteps: 200
batch_size: 128
learning_rate: 0.05
lr_decay: 0.95
mu: 0.9
beta1: 0.9
beta2: 0.999
verbose: true
gradcheckstep: 1.0e-06
num_checks: 3
eps: 1.0e-08
aini: 2.0
bini: 0.1
